name: Generate Metrics

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: nakshicodes
          template: classic
          base: header, activity, community, repositories
          config_timezone: Africa/Nairobi
          plugin_languages: yes
          plugin_languages_limit: 6
          filename: github-metrics.svg
          output_action: gist
          committer_gist: f37aa547bac71088af24f6495a0975ea
